language: node_js
node_js:
  - 10
before_deploy:
  - cd docs
  - npm install
  - npm run build
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: docs/out
  on:
    branch: master
